#!/bin/bash
# install-listener.sh — run approval-listener.sh as a long-lived background service
# so ntfy phone approvals are acted on in near-real-time and survive reboots/crashes.
#
# Prefers a systemd user service; falls back to a nohup-managed background process on
# hosts without systemd. Companion to install-cron.sh.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib-paths.sh
source "${PLUGIN_ROOT}/scripts/lib-paths.sh"
AGENT_DIR="$EA_AGENT_DIR"
LISTENER="${PLUGIN_ROOT}/scripts/approval-listener.sh"
SERVICE_NAME="engineer-agent-listener"
LAUNCHER="${HOME}/.local/bin/engineer-agent-listener"

mkdir -p "${AGENT_DIR}/state"
chmod +x "$LISTENER"

# EA_LISTENER_FROM_CACHE=1 — supervise the MARKETPLACE-INSTALLED copy of the listener rather
# than this checkout, so the running listener and the interactive skills resolve the SAME
# ${CLAUDE_PLUGIN_ROOT}. (Default: this checkout, which is right on a --plugin-dir dev box.)
#
# The service can't name the cache dir directly: it is versioned
# (…/plugins/cache/engineer-agent/engineer-agent/<ver>) and old versions are RETAINED, so a
# plist/unit naming one version keeps running it forever after the next `/plugin update` --
# silently, because approval-listener.sh's mtime self-reexec sees an unchanged file at an
# unchanged path. So point the service at a stable launcher that resolves the highest installed
# version at each launch. Picking up a new version therefore needs a service RESTART (launchctl
# kickstart -k / systemctl --user restart), not a re-install.
if [ "${EA_LISTENER_FROM_CACHE:-0}" = "1" ]; then
  CACHE_ROOT="$(resolve_installed_plugin_root)"
  if [ -z "$CACHE_ROOT" ] || [ ! -f "${CACHE_ROOT}/scripts/approval-listener.sh" ]; then
    echo "ERROR: EA_LISTENER_FROM_CACHE=1 but no installed plugin cache was found." >&2
    echo "  Run '/plugin install engineer-agent' first, or omit the variable to supervise" >&2
    echo "  this checkout (${LISTENER})." >&2
    exit 1
  fi
  mkdir -p "$(dirname "$LAUNCHER")"
  # The version resolution below is duplicated from resolve_installed_plugin_root() in
  # lib-paths.sh rather than sourced: lib-paths.sh lives INSIDE the versioned cache dir, so
  # sourcing it would require the very answer being computed. Keep the two in sync.
  cat > "$LAUNCHER" <<'LAUNCHEOF'
#!/bin/bash
# engineer-agent-listener — stable launcher for the marketplace-installed approval listener.
#
# GENERATED by scripts/install-listener.sh (EA_LISTENER_FROM_CACHE=1). Do not edit by hand;
# re-run that installer to regenerate. Resolves the highest installed plugin version at launch
# so a `/plugin update` is picked up on the next service restart without touching the plist/unit.
set -euo pipefail

base="${CLAUDE_CONFIG_DIR:-${HOME}/.claude}/plugins/cache/engineer-agent/engineer-agent"
root=""
if [ -d "$base" ]; then
  root="$(ls -d "$base"/*/ 2>/dev/null | sort -V | tail -1 | sed 's:/*$::')" || root=""
fi
if [ -z "$root" ] || [ ! -f "${root}/scripts/approval-listener.sh" ]; then
  echo "engineer-agent-listener: no installed engineer-agent plugin found under ${base}" >&2
  exit 1
fi
chmod +x "${root}/scripts/approval-listener.sh" 2>/dev/null || true
exec "${root}/scripts/approval-listener.sh" "$@"
LAUNCHEOF
  chmod +x "$LAUNCHER"
  chmod +x "${CACHE_ROOT}/scripts/approval-listener.sh" 2>/dev/null || true
  LISTENER="$LAUNCHER"
  echo "NOTE: supervising the installed plugin cache via ${LAUNCHER}"
  echo "      (currently resolves to ${CACHE_ROOT})"
fi

# Preflight: jq and a configured command_topic are required for the listener to do anything.
command -v jq >/dev/null 2>&1 || {
  echo "ERROR: jq is required (the listener parses ntfy's JSON stream with it)." >&2
  echo "  Install jq, then re-run this script." >&2
  exit 1
}
if ! grep -q "command_topic" "${AGENT_DIR}/engineer.yaml" 2>/dev/null; then
  echo "WARNING: agent.notify.ntfy.command_topic not found in ${AGENT_DIR}/engineer.yaml." >&2
  echo "  The listener will exit immediately until you configure it (see /engineer-agent setup)." >&2
fi

# Headless auth caveat: like the cron poll, a supervised listener (systemd/nohup) runs outside the
# GUI login session and cannot read the macOS login keychain, so approvals may fail with "Not
# logged in". A launchd LaunchAgent runs in the GUI session but still fails if the keychain locks.
# On a machine with a forceLoginOrgUUID managed policy there is no environment-credential fix (a
# `claude setup-token` OAuth token is rejected too -- see CLAUDE.md); resolve that with your org's IT.
echo "NOTE: a supervised listener runs outside the GUI login session and cannot read the macOS" >&2
echo "      login keychain. If approvals fail with 'Not logged in' or an organization-verification" >&2
echo "      error, see the headless-auth section of CLAUDE.md; on a forceLoginOrgUUID-managed" >&2
echo "      machine there is no environment-credential fix -- work with your org's IT." >&2

# cron/systemd/launchd do not inherit the interactive shell environment. If CLAUDE_BIN
# is set at install time, bake it into the service definition so the listener resolves the
# same binary override when it runs supervised. Each block carries its own trailing newline
# so that when CLAUDE_BIN is unset the generated unit/plist is byte-for-byte unchanged.
SYSTEMD_ENV=""
LAUNCHD_ENV=""
if [ -n "${CLAUDE_BIN:-}" ]; then
  SYSTEMD_ENV="Environment=CLAUDE_BIN=${CLAUDE_BIN}"$'\n'
  LAUNCHD_ENV="    <key>EnvironmentVariables</key>
    <dict>
        <key>CLAUDE_BIN</key>
        <string>${CLAUDE_BIN}</string>
    </dict>
"
fi

if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
  UNIT_DIR="${HOME}/.config/systemd/user"
  mkdir -p "$UNIT_DIR"
  cat > "${UNIT_DIR}/${SERVICE_NAME}.service" <<UNIT
[Unit]
Description=engineer-agent ntfy approval listener
After=network-online.target

[Service]
ExecStart=${LISTENER}
${SYSTEMD_ENV}Restart=always
RestartSec=5

[Install]
WantedBy=default.target
UNIT

  systemctl --user daemon-reload
  systemctl --user enable --now "${SERVICE_NAME}.service"
  # enable --now is a no-op on an already-running unit, so a re-install after a code
  # change would otherwise leave the OLD script running. Force a restart so the
  # supervised process always picks up the current approval-listener.sh (the macOS
  # branch below already reloads via `kickstart -k`).
  systemctl --user restart "${SERVICE_NAME}.service"

  echo "Engineer-agent approval listener installed as a systemd user service:"
  echo "  Unit:   ${UNIT_DIR}/${SERVICE_NAME}.service"
  echo "  Log:    ${AGENT_DIR}/state/approval-listener.log"
  echo ""
  echo "Status:  systemctl --user status ${SERVICE_NAME}"
  echo "Logs:    journalctl --user -u ${SERVICE_NAME} -f"
  echo "Stop:    systemctl --user stop ${SERVICE_NAME}"
  echo "Remove:  systemctl --user disable --now ${SERVICE_NAME} && rm ${UNIT_DIR}/${SERVICE_NAME}.service"
  echo ""
  echo "Tip: for the service to keep running after you log out, enable lingering:"
  echo "  loginctl enable-linger \$USER"
elif [ "$(uname)" = "Darwin" ] && command -v launchctl >/dev/null 2>&1; then
  # macOS: register a launchd LaunchAgent. Like the systemd path, this restarts
  # the listener on crash (KeepAlive) and starts it at login (RunAtLoad).
  LA_DIR="${HOME}/Library/LaunchAgents"
  PLIST="${LA_DIR}/${SERVICE_NAME}.plist"
  LOG_FILE="${AGENT_DIR}/state/approval-listener.log"
  DOMAIN="gui/$(id -u)"
  mkdir -p "$LA_DIR"
  cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${SERVICE_NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${LISTENER}</string>
    </array>
${LAUNCHD_ENV}    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_FILE}</string>
</dict>
</plist>
PLISTEOF

  # Reload idempotently: bootout any prior instance, then bootstrap + kickstart.
  # Fall back to the legacy load/unload API on older macOS where bootstrap is absent.
  launchctl bootout "${DOMAIN}/${SERVICE_NAME}" >/dev/null 2>&1 || true
  if launchctl bootstrap "$DOMAIN" "$PLIST" 2>/dev/null; then
    launchctl kickstart -k "${DOMAIN}/${SERVICE_NAME}" >/dev/null 2>&1 || true
  else
    launchctl unload "$PLIST" >/dev/null 2>&1 || true
    launchctl load -w "$PLIST"
  fi

  echo "Engineer-agent approval listener installed as a launchd LaunchAgent:"
  echo "  Plist:  ${PLIST}"
  echo "  Log:    ${LOG_FILE}"
  echo ""
  echo "Status:  launchctl print ${DOMAIN}/${SERVICE_NAME}"
  echo "Logs:    tail -f ${LOG_FILE}"
  echo "Stop:    launchctl bootout ${DOMAIN}/${SERVICE_NAME}"
  echo "Remove:  launchctl bootout ${DOMAIN}/${SERVICE_NAME}; rm ${PLIST}"
  echo ""
  echo "The LaunchAgent starts at login and restarts on crash automatically."
else
  # Fallback: nohup-managed background process.
  PID_FILE="${AGENT_DIR}/state/approval-listener.pid"
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "Listener already running (PID $(cat "$PID_FILE")). Stop it first:"
    echo "  kill \$(cat ${PID_FILE})"
    exit 0
  fi
  nohup "$LISTENER" >> "${AGENT_DIR}/state/approval-listener.log" 2>&1 &
  echo $! > "$PID_FILE"
  echo "systemd not available — started listener via nohup:"
  echo "  PID:  $(cat "$PID_FILE") (saved to ${PID_FILE})"
  echo "  Log:  ${AGENT_DIR}/state/approval-listener.log"
  echo "  Stop: kill \$(cat ${PID_FILE})"
  echo ""
  echo "NOTE: a nohup process does NOT survive reboot. Re-run this script after reboot,"
  echo "      or add an @reboot crontab entry pointing at ${LISTENER}."
fi
